spring:
  application:
    name: efeito-mulher

  datasource:
    url: jdbc:mysql://root:XrQMpuqxgooJjVyDBvFqVCcgHspDQKSM@switchyard.proxy.rlwy.net:53398/railway?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: XrQMpuqxgooJjVyDBvFqVCcgHspDQKSM

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080

jwt:
  secret: MinhaChaveJWTMuitoSecretaEGrande123!
  expiracao: 86400000